services:
  # Nginx reverse proxy
  # nginx-proxy:
  #   image: jwilder/nginx-proxy
  #   container_name: nginx-proxy
  #   restart: always
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - /var/run/docker.sock:/tmp/docker.sock:ro
  #     - ./certs:/etc/nginx/certs
  #     - ./vhost:/etc/nginx/vhost.d
  #     - ./html:/usr/share/nginx/html

  # Frontend 
  frontend:
    container_name: frontend
    build:
      context: ./frontend 
      dockerfile: frontend.dockerfile  
    restart: always
    ports:
      - 3000:3000

  # Backend 
  backend:
    container_name: backend
    build:
      context: ./backend 
      dockerfile: backend.dockerfile  
    restart: always
    ports:
      - 4000:4000
